name = "hax_basic"
version = "0.1.0"
defaultTargets = ["hax_basic"]

[[lean_lib]]
name = "hax_basic"
roots = ["extraction.hax_basic"]

[[require]]
name = "Hax"
git.url = "https://github.com/cryspen/hax"
git.subDir = "hax-lib/proof-libs/lean"
rev = "main"